from __future__ import annotations


UNSAFE_DOCUMENT_PATTERNS: dict[str, list[str]] = {
    "legal_risk_language": [
        "this is legal advice",
        "no attorney needed",
        "attorney-client relationship",
        "legally guaranteed",
        "legally binding advice",
    ],
    "executable_contract_language": [
        "execute this contract automatically",
        "auto execute",
        "signature block generated by system",
    ],
    "guaranteed_closing_profit": [
        "guaranteed close",
        "guaranteed closing",
        "guaranteed profit",
        "risk-free return",
    ],
    "pressure_deceptive_language": [
        "you must sign",
        "last chance",
        "do not talk to anyone else",
        "buyers are fighting over this",
    ],
    "unsupported_arv_repair_claim": [
        "fake arv",
        "inflate arv",
        "hide repair costs",
        "make repairs lower",
    ],
    "hidden_assignment_deception": [
        "hide assignment fee",
        "do not disclose assignment",
        "do not mention our role",
    ],
}


def scan_document_text(text: str) -> dict[str, object]:
    lowered = text.lower()
    flags = sorted(
        {
            category
            for category, phrases in UNSAFE_DOCUMENT_PATTERNS.items()
            if any(phrase in lowered for phrase in phrases)
        }
    )
    return {
        "allowed": not flags,
        "risk_flags": flags,
        "blocked_reason": ", ".join(flags),
        "legal_advice_provided": False,
        "executable_contract_generated": False,
        "portal_publish_allowed": False,
    }


def issue_for_safety_flag(flag: str) -> dict[str, object]:
    severity = "high" if flag in {"legal_risk_language", "executable_contract_language"} else "medium"
    return {
        "issue_type": flag,
        "severity": severity,
        "source_field": "document_text",
        "explanation": f"Document text contains {flag.replace('_', ' ')} and must be routed for review.",
        "recommended_next_action": "Queue owner/compliance review; do not answer as legal guidance or execute anything.",
        "owner_review_required": True,
        "compliance_review_required": True,
        "external_review_reminder": flag in {"legal_risk_language", "executable_contract_language"},
    }

