import { notFound } from "next/navigation";
import { MetricCard } from "@/components/MetricCard";
import { PageHeader } from "@/components/PageHeader";
import { Pill } from "@/components/Pill";
import { RecordCard } from "@/components/RecordCard";
import { Section } from "@/components/Section";
import {
  formatCurrency,
  getClosingCoordinationChecklist,
  getContractControl,
  getDeal,
  getDealRoomBlockers,
  getLead,
  getUnifiedDealRoom,
  unifiedDealRooms
} from "@/lib/demo-data";

const checklistRows = [
  ["Seller accepted offer", "sellerAcceptedOffer"],
  ["Contract prep ready", "contractPrepReady"],
  ["Buyer matched", "buyerMatched"],
  ["Buyer POF verified", "buyerPofVerified"],
  ["Assignment allowed", "assignmentAllowedConfirmed"],
  ["Title handoff prepared", "titleHandoffPrepared"],
  ["Inspection/access coordinated", "inspectionAccessCoordinated"],
  ["Seller documents requested", "sellerDocumentsRequested"],
  ["Buyer intent recorded", "buyerIntentRecorded"],
  ["Compliance review complete", "complianceReviewComplete"],
  ["Owner approval complete", "ownerApprovalComplete"]
] as const;

export function generateStaticParams() {
  return unifiedDealRooms.map((room) => ({ dealRoomId: room.id }));
}

export default async function DealRoomDetailPage({ params }: { params: Promise<{ dealRoomId: string }> }) {
  const { dealRoomId } = await params;
  const room = getUnifiedDealRoom(dealRoomId);
  if (!room) notFound();
  const deal = getDeal(room.dealId);
  const lead = deal ? getLead(deal.leadId) : undefined;
  const contract = getContractControl(room.contractControlId);
  const checklist = getClosingCoordinationChecklist(room.id);
  const blockers = getDealRoomBlockers(room.id);

  return (
    <div className="page">
      <PageHeader
        eyebrow={room.coordinationStatus}
        title={`${room.id} / ${lead?.city ?? "Property"}, ${lead?.state ?? ""}`}
        description="This internal room coordinates portal status, contract control, title handoff, communications, and assignment readiness without executing contracts or submitting anything externally."
      />
      <div className="metric-grid">
        <MetricCard label="Coordination status" value={room.coordinationStatus} detail={room.ownerApprovalStatus} />
        <MetricCard label="Open blockers" value={String(blockers.filter((blocker) => !blocker.resolved).length)} detail="Generated by closing gate" />
        <MetricCard label="Fee at risk" value={formatCurrency(room.projectedAssignmentFeeAtRisk)} detail="Internal only" />
        <MetricCard label="Closing timeline" value={room.closingTimeline || "missing"} detail="Owner maintained" />
      </div>

      <div className="grid-two">
        <Section title="Connected Records">
          <div className="record-list">
            <RecordCard title="Deal" meta={`${room.dealId} / ${lead?.propertyType ?? "property"}`} right={<Pill>{deal?.status ?? "missing"}</Pill>} />
            <RecordCard title="Contract control" meta={contract?.contractStatus ?? "missing"} right={<Pill tone={contract?.contractPrepAllowed ? "green" : "red"}>{room.contractControlId}</Pill>} />
            <RecordCard title="Seller offer room" meta={room.sellerOfferPublicationId ?? "missing"} right={<Pill tone={room.sellerPortalStatus === "visible" ? "green" : "red"}>{room.sellerPortalStatus}</Pill>} />
            <RecordCard title="Buyer deal room" meta={room.buyerDealPublicationId ?? "missing"} right={<Pill tone={room.buyerPortalStatus === "visible" ? "green" : "red"}>{room.buyerPortalStatus}</Pill>} />
            <RecordCard title="Title handoff" meta={room.titleHandoffPacketId ?? "missing"} right={<Pill tone={room.titleHandoffStatus === "draft_ready" ? "green" : "gold"}>{room.titleHandoffStatus}</Pill>} />
            <RecordCard title="Assignment readiness" meta={room.assignmentReadinessRecordId ?? "missing"} right={<Pill tone={room.assignmentReadinessStatus === "assignment_ready" ? "green" : "red"}>{room.assignmentReadinessStatus}</Pill>} />
          </div>
        </Section>

        <Section title="Next Required Actions">
          <div className="record-list">
            {room.nextRequiredActions.length ? room.nextRequiredActions.map((action) => (
              <RecordCard key={action} title={action} meta="Internal recommendation only" right={<Pill tone="gold">recommend</Pill>} />
            )) : <RecordCard title="No next action blockers" meta="Closing coordination gate is clear." right={<Pill tone="green">clear</Pill>} />}
            <RecordCard title="Safety lock" meta="No title submission, payment handling, legal execution, or automatic negotiation." right={<Pill tone="red">locked</Pill>} />
          </div>
        </Section>
      </div>

      <Section title="Closing Coordination Checklist">
        <table className="data-table">
          <thead>
            <tr>
              <th>Checklist Item</th>
              <th>Status</th>
              <th>Gate</th>
            </tr>
          </thead>
          <tbody>
            {checklistRows.map(([label, key]) => {
              const passed = Boolean(checklist?.[key]);
              return (
                <tr key={key}>
                  <td>{label}</td>
                  <td><Pill tone={passed ? "green" : "red"}>{passed ? "complete" : "missing"}</Pill></td>
                  <td>{passed ? "clear" : "blocks closing readiness"}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </Section>

      <Section title="Blocker Records">
        <div className="record-list">
          {blockers.length ? blockers.map((blocker) => (
            <RecordCard
              key={blocker.id}
              title={blocker.blockerType}
              meta={`${blocker.detail} Recommendation: ${blocker.recommendation}.`}
              right={<Pill tone={blocker.severity === "critical" ? "red" : "gold"}>{blocker.severity}</Pill>}
            />
          )) : <RecordCard title="No blockers" meta="The room is closing-ready under the current coordination checklist." right={<Pill tone="green">clear</Pill>} />}
        </div>
      </Section>
    </div>
  );
}
