from __future__ import annotations


CLIENT_COMMAND_BLOCKED_ACTIONS = {
    "sms_send": "Client command CP1-CP12 cannot send SMS without passing explicit source gates.",
    "email_send": "Client command CP1-CP12 cannot send email without passing explicit source gates.",
    "voice_call": "Client command CP1-CP12 cannot place voice calls.",
    "buyer_blast": "Client command CP1-CP12 cannot blast buyers.",
    "seller_blast": "Client command CP1-CP12 cannot blast sellers.",
    "campaign_launch": "Client command CP1-CP12 cannot launch campaigns.",
    "auto_follow_up": "Client command CP1-CP12 cannot run autonomous follow-up.",
    "auto_reply": "Client command CP1-CP12 cannot auto-reply to clients, buyers, or sellers.",
    "bulk_send": "Client command CP1-CP12 cannot send bulk messages.",
    "buyer_scraping": "Client command CP1-CP12 cannot scrape or pull buyer lists.",
    "skip_trace_provider_call": "Skip-trace provider calls are unavailable in CP1-CP12.",
    "dnc_check_provider_call": "DNC provider calls are unavailable in CP1-CP12.",
    "ten_dlc_live_registration": "10DLC live registration is unavailable in CP1-CP12.",
    "live_comp_property_data_pull": "Live comp, property, tax, title, and MLS provider pulls are unavailable in CP1-CP12.",
    "tax_title_provider_call": "Tax and title provider calls are unavailable in CP1-CP12.",
    "mls_call": "MLS calls are unavailable in CP1-CP12.",
    "stripe_charge": "Billing and payment actions are unavailable in CP1-CP12 without explicit billing gates.",
    "collect_payment": "Payment collection is unavailable in CP1-CP12 without explicit billing gates.",
    "billing_activation": "Billing activation is unavailable in CP1-CP12.",
    "invoice_action": "Invoice actions are unavailable in CP1-CP12.",
    "create_stripe_customer": "Stripe customer creation is unavailable in CP1-CP12 without explicit billing gates.",
    "subscription_start": "Subscription creation is unavailable in CP1-CP12 without explicit billing gates.",
    "refund_action": "Refund actions are unavailable in CP1-CP12.",
    "store_card": "Raw card storage is forbidden in Client Command.",
    "contract_generation": "Contract generation is unavailable in CP1-CP12.",
    "contract_esignature_send": "Contract and e-signature sends are unavailable in CP1-CP12.",
    "provider_sync": "Provider sync actions are unavailable in CP1-CP12.",
    "live_provider_activation": "Live provider activation is unavailable in CP1-CP12.",
    "force_send": "Forced communication sends are unavailable in Client Command.",
    "force_charge": "Forced billing actions are unavailable in Client Command.",
    "override_gate": "Client Command cannot override source safety gates.",
    "delete_client_data": "Unsafe destructive client data actions are unavailable in Client Command.",
    "autonomous_fulfillment": "Autonomous fulfillment is unavailable in CP1-CP12.",
    "legal_advice": "Client command cannot provide legal advice.",
    "fake_roi_claim": "Client command cannot make unsupported ROI claims.",
    "guaranteed_buyer_claim": "Client command cannot claim a guaranteed buyer or assignment fee.",
    "prime_governance_access": "Client command cannot expose internal Prime governance.",
    "provider_payload_access": "Client command cannot expose provider payload internals.",
}


UNSAFE_CLIENT_LANGUAGE = {
    "legal advice": "legal_advice",
    "guaranteed roi": "fake_roi_claim",
    "guaranteed return": "fake_roi_claim",
    "guaranteed profit": "fake_roi_claim",
    "guarantee profit": "fake_roi_claim",
    "guaranteed assignment fee": "guaranteed_buyer_claim",
    "guaranteed buyer": "guaranteed_buyer_claim",
    "risk-free": "fake_roi_claim",
    "you must sell": "legal_advice",
    "contact seller": "seller_blast",
    "send sms": "sms_send",
    "send email": "email_send",
    "call now": "voice_call",
    "auto dial": "voice_call",
    "call seller now": "voice_call",
    "buyer blast": "buyer_blast",
    "blast buyers": "buyer_blast",
    "contact buyer": "buyer_blast",
    "contact all": "bulk_send",
    "market deal": "campaign_launch",
    "launch campaign": "campaign_launch",
    "start campaign": "campaign_launch",
    "launch drip": "campaign_launch",
    "send deal": "email_send",
    "send bulk": "bulk_send",
    "auto follow-up": "auto_follow_up",
    "auto reply": "auto_reply",
    "scrape buyers": "buyer_scraping",
    "pull buyer list": "buyer_scraping",
    "run skip trace": "skip_trace_provider_call",
    "pull skip trace": "skip_trace_provider_call",
    "check dnc live": "dnc_check_provider_call",
    "register 10dlc live": "ten_dlc_live_registration",
    "pull live comps": "live_comp_property_data_pull",
    "mls": "mls_call",
    "title provider": "tax_title_provider_call",
    "charge card": "stripe_charge",
    "charge": "stripe_charge",
    "charge now": "stripe_charge",
    "collect payment": "collect_payment",
    "activate billing": "billing_activation",
    "activate live": "live_provider_activation",
    "invoice": "invoice_action",
    "bill client": "invoice_action",
    "create stripe customer": "create_stripe_customer",
    "start subscription": "subscription_start",
    "auto subscribe": "subscription_start",
    "auto upgrade": "subscription_start",
    "auto downgrade": "subscription_start",
    "refund": "refund_action",
    "store card": "store_card",
    "generate contract": "contract_generation",
    "send contract": "contract_esignature_send",
    "send offer": "email_send",
    "e-sign": "contract_esignature_send",
    "sync to provider": "provider_sync",
    "force send": "force_send",
    "force charge": "force_charge",
    "override gate": "override_gate",
    "bypass compliance": "override_gate",
    "execute provider": "provider_sync",
    "delete client data": "delete_client_data",
    "auto billing": "billing_activation",
    "dispatch agent": "autonomous_fulfillment",
    "execute": "autonomous_fulfillment",
}


def client_command_safety_rules() -> dict[str, object]:
    return {
        "phase": "CP1-CP12 controlled client command operating system",
        "outbound_provider_actions_allowed": False,
        "billing_allowed": False,
        "contract_esign_allowed": False,
        "contract_generation_allowed": False,
        "live_property_data_pull_allowed": False,
        "provider_sync_allowed": False,
        "buyer_blast_allowed": False,
        "seller_blast_allowed": False,
        "campaign_launch_allowed": False,
        "buyer_scraping_allowed": False,
        "dnc_provider_checks_allowed": False,
        "ten_dlc_live_registration_allowed": False,
        "autonomous_fulfillment_allowed": False,
        "legal_advice_allowed": False,
        "prime_governance_visible": False,
        "provider_payload_internals_visible": False,
        "blocked_actions": CLIENT_COMMAND_BLOCKED_ACTIONS,
    }


def validate_client_safe_text(text: str) -> dict[str, object]:
    lowered = text.lower()
    flags = sorted({flag for phrase, flag in UNSAFE_CLIENT_LANGUAGE.items() if phrase in lowered})
    return {
        "allowed": not flags,
        "risk_flags": flags,
        "blocked_reason": ", ".join(flags),
    }
