export const dashboardRoutes = [
  { href: "/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { href: "/dashboard/command-center", label: "Command Center", icon: "Command" },
  { href: "/dashboard/client-command", label: "Client Command", icon: "Building2" },
  { href: "/dashboard/client-command/acquisition", label: "Client Acquisition", icon: "PhoneCall" },
  { href: "/dashboard/client-command/underwriting", label: "Client Underwriting", icon: "Calculator" },
  { href: "/dashboard/client-command/disposition", label: "Client Disposition", icon: "Handshake" },
  { href: "/dashboard/client-command/compliance", label: "Client Compliance", icon: "ShieldCheck" },
  { href: "/dashboard/client-command/reports", label: "Client Reports", icon: "FileText" },
  { href: "/dashboard/first-deal-cockpit", label: "First Deal Cockpit", icon: "ClipboardList" },
  { href: "/dashboard/autonomy", label: "Autonomy", icon: "Command" },
  { href: "/dashboard/auto-execution", label: "Auto Execution", icon: "TimerReset" },
  { href: "/dashboard/ai", label: "AI Gateway", icon: "Bot" },
  { href: "/dashboard/worker", label: "Worker Runtime", icon: "TimerReset" },
  { href: "/dashboard/command-hierarchy", label: "Hierarchy", icon: "Network" },
  { href: "/dashboard/overseer", label: "Prime 2", icon: "Crown" },
  { href: "/dashboard/divisions", label: "Divisions", icon: "Building2" },
  { href: "/dashboard/managers", label: "Managers", icon: "BriefcaseBusiness" },
  { href: "/dashboard/manager-queue", label: "Manager Queue", icon: "ListChecks" },
  { href: "/dashboard/agents", label: "Agents", icon: "Bot" },
  { href: "/dashboard/leads", label: "Leads", icon: "MapPinned" },
  { href: "/dashboard/lead-imports", label: "Lead Imports", icon: "FileCheck2" },
  { href: "/dashboard/lead-qa", label: "Lead QA", icon: "ShieldCheck" },
  { href: "/dashboard/call-outcomes", label: "Call Outcomes", icon: "PhoneCall" },
  { href: "/dashboard/call-intelligence", label: "Call Intelligence", icon: "PhoneCall" },
  { href: "/dashboard/field-testing", label: "Field Testing", icon: "ClipboardList" },
  { href: "/dashboard/deals", label: "Deals", icon: "BadgeDollarSign" },
  { href: "/dashboard/underwriting", label: "Underwriting", icon: "Calculator" },
  { href: "/dashboard/profit-control", label: "Profit Control", icon: "CircleDollarSign" },
  { href: "/dashboard/seller-acquisition", label: "Seller Acquisition", icon: "PhoneCall" },
  { href: "/dashboard/seller-followups", label: "Seller Follow-Ups", icon: "Clock3" },
  { href: "/dashboard/follow-up-control", label: "Follow-Up Control", icon: "TimerReset" },
  { href: "/dashboard/offer-packets", label: "Offer Packets", icon: "FileCheck2" },
  { href: "/dashboard/contract-control", label: "Contract Control", icon: "FileCheck2" },
  { href: "/dashboard/title-handoff", label: "Title Handoff", icon: "ClipboardList" },
  { href: "/dashboard/assignment-readiness", label: "Assignment Readiness", icon: "ShieldCheck" },
  { href: "/dashboard/communications", label: "Communications", icon: "Command" },
  { href: "/dashboard/deal-room", label: "Deal Room", icon: "Network" },
  { href: "/dashboard/closing-coordination", label: "Closing Coordination", icon: "ListChecks" },
  { href: "/dashboard/deal-evidence", label: "Deal Evidence", icon: "ClipboardList" },
  { href: "/dashboard/documents", label: "Documents", icon: "FileCheck2" },
  { href: "/dashboard/assignment-fees", label: "Assignment Fees", icon: "CircleDollarSign" },
  { href: "/dashboard/buyer-demand", label: "Buyer Demand", icon: "UsersRound" },
  { href: "/dashboard/deal-distribution", label: "Deal Distribution", icon: "ClipboardList" },
  { href: "/dashboard/buyer-priority", label: "Buyer Priority", icon: "Handshake" },
  { href: "/dashboard/buyer-acceleration", label: "Buyer Acceleration", icon: "TimerReset" },
  { href: "/dashboard/optimization", label: "Optimization", icon: "Command" },
  { href: "/dashboard/feedback-loop", label: "Feedback Loop", icon: "TimerReset" },
  { href: "/dashboard/scoring-adjustments", label: "Scoring Adjustments", icon: "Calculator" },
  { href: "/dashboard/field-briefing", label: "Field Briefing", icon: "ClipboardList" },
  { href: "/dashboard/revenue-forecast", label: "Revenue Forecast", icon: "CircleDollarSign" },
  { href: "/dashboard/market-scaling", label: "Market Scaling", icon: "MapPinned" },
  { href: "/dashboard/lead-spend-planner", label: "Lead Spend", icon: "Calculator" },
  { href: "/dashboard/operator-mode", label: "Operator Mode", icon: "Command" },
  { href: "/dashboard/production-readiness", label: "Production Readiness", icon: "ShieldCheck" },
  { href: "/dashboard/cloud-readiness", label: "Cloud Readiness", icon: "ShieldCheck" },
  { href: "/dashboard/live-activation", label: "Live Activation", icon: "ShieldCheck" },
  { href: "/dashboard/audit-exports", label: "Audit Exports", icon: "ClipboardList" },
  { href: "/dashboard/provider-readiness", label: "Provider Readiness", icon: "ShieldCheck" },
  { href: "/dashboard/campaigns", label: "Campaign Brain", icon: "Command" },
  { href: "/dashboard/market-enrichment", label: "Market Enrichment", icon: "MapPinned" },
  { href: "/dashboard/market-ranking", label: "Market Ranking", icon: "MapPinned" },
  { href: "/dashboard/prime-memory", label: "Prime Memory", icon: "Bot" },
  { href: "/dashboard/learning-signals", label: "Learning Signals", icon: "TimerReset" },
  { href: "/dashboard/playbook-recommendations", label: "Playbooks", icon: "ClipboardList" },
  { href: "/dashboard/backups", label: "Backups", icon: "FileCheck2" },
  { href: "/dashboard/offer-conversion", label: "Offer Conversion", icon: "FileCheck2" },
  { href: "/dashboard/negotiations", label: "Negotiations", icon: "ListChecks" },
  { href: "/dashboard/contract-ready", label: "Contract Ready", icon: "ShieldCheck" },
  { href: "/dashboard/title-review", label: "Title Review", icon: "ClipboardList" },
  { href: "/dashboard/review-packets", label: "Review Packets", icon: "FileCheck2" },
  { href: "/dashboard/buyers", label: "Cash Buyers", icon: "UsersRound" },
  { href: "/dashboard/buyer-matches", label: "Buyer Matches", icon: "Handshake" },
  { href: "/dashboard/compliance", label: "Compliance", icon: "ShieldCheck" },
  { href: "/dashboard/daily-briefing", label: "Daily Briefing", icon: "ClipboardList" }
];
