export const dashboardRoutes = [
  { href: "/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { href: "/dashboard/command-center", label: "Command Center", icon: "Command" },
  { href: "/dashboard/command-hierarchy", label: "Hierarchy", icon: "Network" },
  { href: "/dashboard/overseer", label: "Wholesale Prime", icon: "Crown" },
  { href: "/dashboard/divisions", label: "Divisions", icon: "Building2" },
  { href: "/dashboard/managers", label: "Managers", icon: "BriefcaseBusiness" },
  { href: "/dashboard/manager-queue", label: "Manager Queue", icon: "ListChecks" },
  { href: "/dashboard/agents", label: "Agents", icon: "Bot" },
  { href: "/dashboard/leads", label: "Leads", icon: "MapPinned" },
  { href: "/dashboard/deals", label: "Deals", icon: "BadgeDollarSign" },
  { href: "/dashboard/underwriting", label: "Underwriting", icon: "Calculator" },
  { href: "/dashboard/profit-control", label: "Profit Control", icon: "CircleDollarSign" },
  { href: "/dashboard/seller-acquisition", label: "Seller Acquisition", icon: "PhoneCall" },
  { href: "/dashboard/seller-followups", label: "Seller Follow-Ups", icon: "Clock3" },
  { href: "/dashboard/follow-up-control", label: "Follow-Up Control", icon: "TimerReset" },
  { href: "/dashboard/offer-packets", label: "Offer Packets", icon: "FileCheck2" },
  { href: "/dashboard/contract-control", label: "Contract Control", icon: "FileCheck2" },
  { href: "/dashboard/title-handoff", label: "Title Handoff", icon: "ClipboardList" },
  { href: "/dashboard/assignment-readiness", label: "Assignment Readiness", icon: "ShieldCheck" },
  { href: "/dashboard/communications", label: "Communications", icon: "Command" },
  { href: "/dashboard/deal-room", label: "Deal Room", icon: "Network" },
  { href: "/dashboard/closing-coordination", label: "Closing Coordination", icon: "ListChecks" },
  { href: "/dashboard/deal-evidence", label: "Deal Evidence", icon: "ClipboardList" },
  { href: "/dashboard/assignment-fees", label: "Assignment Fees", icon: "CircleDollarSign" },
  { href: "/dashboard/buyer-demand", label: "Buyer Demand", icon: "UsersRound" },
  { href: "/dashboard/deal-distribution", label: "Deal Distribution", icon: "ClipboardList" },
  { href: "/dashboard/buyer-priority", label: "Buyer Priority", icon: "Handshake" },
  { href: "/dashboard/offer-conversion", label: "Offer Conversion", icon: "FileCheck2" },
  { href: "/dashboard/negotiations", label: "Negotiations", icon: "ListChecks" },
  { href: "/dashboard/contract-ready", label: "Contract Ready", icon: "ShieldCheck" },
  { href: "/dashboard/buyers", label: "Cash Buyers", icon: "UsersRound" },
  { href: "/dashboard/buyer-matches", label: "Buyer Matches", icon: "Handshake" },
  { href: "/dashboard/compliance", label: "Compliance", icon: "ShieldCheck" },
  { href: "/dashboard/daily-briefing", label: "Daily Briefing", icon: "ClipboardList" }
];
